server:
  port: 8081

spring:
  redis:
    host: 172.19.58.36
    port: 6379
  cloud:
    gateway:
      routes:
      - id: route
        uri: http://localhost:8082
        predicates:
        - Path=/api/**
        filters:
        ## 限流
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 10
            redis-rate-limiter.burstCapacity: 20
            key-resolver: "#{@apiKeyResolver}"
        ## 去掉url第一个前缀 /api/test/gateway --》 /test/gateway
        - StripPrefix=1