server:
  port: 8081

spring:
  redis:
    host: 10.23.241.251
    port: 7001
  cloud:
    gateway:
      metrics:
        enabled: true
      routes:
      - id: route
        uri: http://localhost:8082
        predicates:
        - Path=/api/**
        filters:
        ## 限流
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 100000
            redis-rate-limiter.burstCapacity: 200000
            key-resolver: "#{@apiKeyResolver}"
        ## 去掉url第一个前缀 /api/test/gateway --》 /test/gateway
        - StripPrefix=1